### ISSUE TITLE
Çok Teşekkür Ederim

### ISSUE THREAD

**Issue by Dukalipse** [muratcesmecioglu/Kuveytturk-POS-Plugin#1]
Merhaba,
Böyle Bir eklentiyi, Geliştirip ücretsiz sunmanız harika. Çok Teşekkür ederim. Ufak Bir sorun var, Bunu paylaşmak istedim.
Son kullanma tarihi ve yıl seçeneklerinin ordaki kutucukta 2 şertane ok işareti çıkmakta bilginiz olsun.
![sorun](https://user-images.githubusercontent.com/68149381/87222720-ec8a3e80-c37e-11ea-9c3d-cc4db01b856f.jpg)

**Comment by muratcesmecioglu** [comment]
Merhaba.

Temanızdaki CSS ile ilgili bir sorun olabilir. Bu paylaştığım sürüm ücretsiz olduğu için ekstra bir css eklemedim. Ufak tefek ayarlamaları sizin yapmanız gerekmekte.

CSS dosyanızı düzenleyip oradaki kutuların select etiketine `-moz-appearance: none;` ve `-webkit-appearance: none;` verilip çözülebilir. Denemek lazım.

**Comment by Dukalipse** [comment]
Cevabın için Teşekkür ederim. Pek fazla Teknik bilgiye sahip değilim. Büyük bir sorun yaratmıyor. Böylede kullanılabilir. Çok Teşekkür ederim.
